<?php /* @var $this Aoe_Static_Block_Beforebodyend */?>
<script type="text/javascript">
//<![CDATA[
	var AJAXHOME_URL = '<?php echo Mage::getUrl('phone/call/index', Mage::app()->getStore()->isCurrentlySecure() ? array('_secure' => 1) : array()) ?>';
	var FULLACTIONNAME = '<?php echo $this->getAction()->getFullActionName() ?>';
	<?php // This will report the current product id back to the server for the recently viewed product feature ?>
	<?php // TODO: rewrite recently viewed products feature to be handled client side using localStorage. In this case more data needs to be added here and stored in the client ?>
	<?php if (($_product = Mage::registry('product')) == true) : ?>var CURRENTPRODUCTID = '<?php echo $_product->getId() ?>';<?php endif; ?>
//]]>
</script>
