<?php
/* @var $this Aoe_Static_Block_Adminhtml_Purge */
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Purge Urls from AOE Static Cache') ?></h3></td>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Purge Tags from AOE Static Cache') ?></h3></td>
        </tr>
    </table>
</div>

<table class="form-list" style="width: 98%">
    <tbody>
        <tr>
            <td>
                <form action="<?php echo $this->getUrl('*/*/*') ?>" method="post">
                    <textarea rows="3" cols="100" name="aoe_purge_urls"></textarea>
                    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
                    <br/>
                    <button type="submit"><?php echo $this->__('Purge Urls') ?></button>
                </form>
            </td>
            <td>
                <form action="<?php echo $this->getUrl('*/*/*') ?>" method="post">
                    <textarea rows="3" cols="100" name="aoe_purge_tags"></textarea>
                    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
                    <br/>
                    <button type="submit"><?php echo $this->__('Purge Tags') ?></button>
                </form>
            </td>
        </tr>
    </tbody>
</table>
x
