<?php /* @var $this Aoe_Static_Block_Beforebodyend */?>
<script type="text/javascript">
    <?php // TODO: rewrite recently viewed products feature to be handled client side using localStorage. In this case more data needs to be added here and stored in the client ?>
    Aoe_Static.init(
        '<?php echo Mage::getUrl('aoestatic/call/index', Mage::app()->getStore()->isCurrentlySecure() ? array('_secure' => 1) : array()) ?>',
        '<?php echo $this->getAction()->getFullActionName() ?>',
        '<?php echo Mage::app()->getStore()->getId() ?>',
        '<?php echo Mage::app()->getWebsite()->getId() ?>',
        <?php // This will report the current product id back to the server for the recently viewed product feature ?>
        <?php echo ((($_product = Mage::registry('product')) == true) ? $_product->getId() : 0) ?>
    );
</script>
